import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";
import type { ResponsiveUtils } from "@/lib/responsive";

export function createStyles(r: ResponsiveUtils) {
  return StyleSheet.create({
    overlay: {
      flex: 1,
      justifyContent: "flex-end",
    },
    backdrop: {
      flex: 1,
      backgroundColor: Colors.overlay,
    },
    sheet: {
      backgroundColor: Colors.surface,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      paddingBottom: r.rs(40),
      paddingHorizontal: r.rs(20),
    },
    grabber: {
      width: 36,
      height: 4,
      borderRadius: 2,
      backgroundColor: Colors.border,
      alignSelf: "center",
      marginTop: 12,
      marginBottom: 16,
    },
    photo: {
      width: "100%",
      height: r.rs(160),
      borderRadius: 12,
    },
    photoCard: {
      marginBottom: 16,
      position: "relative",
    },
    photoPreviewBtn: {
      borderRadius: 12,
      overflow: "hidden",
    },
    photoPreviewHint: {
      position: "absolute",
      left: 12,
      bottom: 12,
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: "rgba(15, 23, 42, 0.72)",
    },
    photoPreviewHintText: {
      fontSize: r.rf(12),
      fontFamily: "Inter_600SemiBold",
      color: "#FFF",
    },
    photoEditIconBtn: {
      position: "absolute",
      top: 12,
      right: 12,
      width: Math.max(r.rs(40), 44),
      height: Math.max(r.rs(40), 44),
      borderRadius: Math.max(r.rs(20), 22),
      backgroundColor: "rgba(255,255,255,0.95)",
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.12,
      shadowRadius: 6,
      elevation: 3,
    },
    photoActionDisabled: {
      opacity: 0.6,
    },
    photoPlaceholder: {
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: Colors.primary,
      borderStyle: "dashed",
      backgroundColor: Colors.primaryLight,
      paddingHorizontal: 20,
      paddingVertical: r.rs(24),
      marginBottom: 16,
      gap: 10,
    },
    photoPlaceholderIcon: {
      width: r.rs(52),
      height: r.rs(52),
      borderRadius: 16,
      backgroundColor: "#FFF",
      alignItems: "center",
      justifyContent: "center",
    },
    photoPlaceholderTitle: {
      fontSize: r.rf(16),
      fontFamily: "Inter_700Bold",
      color: Colors.primary,
    },
    photoPlaceholderSubtitle: {
      fontSize: r.rf(13),
      fontFamily: "Inter_400Regular",
      color: Colors.textSecondary,
      textAlign: "center",
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      marginBottom: 16,
    },
    headerText: {
      flex: 1,
    },
    title: {
      fontSize: r.rf(20),
      fontFamily: "Inter_700Bold",
      color: Colors.text,
    },
    subtitle: {
      fontSize: r.rf(13),
      fontFamily: "Inter_400Regular",
      color: Colors.textSecondary,
      marginTop: 2,
    },
    stats: {
      gap: 10,
      marginBottom: 20,
    },
    stat: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    statText: {
      fontSize: r.rf(14),
      fontFamily: "Inter_500Medium",
      color: Colors.textSecondary,
    },
    actions: {
      flexDirection: "row",
      gap: 12,
      marginBottom: 16,
    },
    actionBtn: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      paddingVertical: r.rs(12),
      borderRadius: 12,
      minHeight: 44,
    },
    navigateBtn: {
      backgroundColor: Colors.primary,
    },
    photoBtn: {
      backgroundColor: Colors.primaryLight,
    },
    actionBtnTextLight: {
      fontSize: r.rf(14),
      fontFamily: "Inter_600SemiBold",
      color: "#FFF",
    },
    actionBtnText: {
      fontSize: r.rf(14),
      fontFamily: "Inter_600SemiBold",
      color: Colors.primary,
    },
    confirmBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      paddingVertical: r.rs(14),
      borderRadius: 12,
      backgroundColor: Colors.success,
      minHeight: 48,
    },
    confirmBtnDisabled: {
      opacity: 0.6,
    },
    confirmBtnText: {
      fontSize: r.rf(15),
      fontFamily: "Inter_600SemiBold",
      color: "#FFF",
    },
    tooFarText: {
      textAlign: "center",
      fontSize: r.rf(13),
      fontFamily: "Inter_400Regular",
      color: Colors.textTertiary,
      marginTop: 4,
    },
    fullPhotoContainer: {
      flex: 1,
      backgroundColor: "#000",
      justifyContent: "center",
      alignItems: "center",
    },
    closePhotoBtn: {
      position: "absolute",
      top: 60,
      right: 20,
      zIndex: 10,
      width: r.rs(44),
      height: r.rs(44),
      borderRadius: r.rs(22),
      backgroundColor: "rgba(0,0,0,0.6)",
      alignItems: "center",
      justifyContent: "center",
    },
    fullPhoto: {
      width: "100%",
      height: "80%",
    },
  });
}
