import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";
import type { ResponsiveUtils } from "@/lib/responsive";

export function createStyles(r: ResponsiveUtils) {
  return StyleSheet.create({
    overlay: {
      flex: 1,
      flexDirection: "row",
    },
    drawer: {
      width: r.drawerWidth,
      backgroundColor: Colors.surface,
      shadowColor: "#000",
      shadowOffset: { width: 4, height: 0 },
      shadowOpacity: 0.15,
      shadowRadius: 16,
      elevation: 12,
    },
    drawerContent: {
      paddingHorizontal: r.rs(20),
      paddingTop: 8,
    },
    backdrop: {
      flex: 1,
      backgroundColor: Colors.overlay,
    },
    backdropTouchable: {
      flex: 1,
    },
    closeBtn: {
      position: "absolute",
      top: 54,
      right: 12,
      width: r.rs(36),
      height: r.rs(36),
      borderRadius: r.rs(18),
      backgroundColor: Colors.surfaceSecondary,
      alignItems: "center",
      justifyContent: "center",
    },
    profileSection: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      marginBottom: 4,
    },
    avatar: {
      width: r.rs(48),
      height: r.rs(48),
      borderRadius: r.rs(24),
    },
    avatarPlaceholder: {
      width: r.rs(48),
      height: r.rs(48),
      borderRadius: r.rs(24),
      backgroundColor: Colors.surfaceSecondary,
      alignItems: "center",
      justifyContent: "center",
    },
    profileInfo: {
      flex: 1,
    },
    name: {
      fontSize: r.rf(16),
      fontFamily: "Inter_600SemiBold",
      color: Colors.text,
    },
    email: {
      fontSize: r.rf(13),
      fontFamily: "Inter_400Regular",
      color: Colors.textSecondary,
      marginTop: 2,
    },
    guestLabel: {
      fontSize: r.rf(13),
      fontFamily: "Inter_400Regular",
      color: Colors.textTertiary,
      marginTop: 2,
    },
    divider: {
      height: 1,
      backgroundColor: Colors.borderLight,
      marginVertical: 10,
    },
    menuItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingVertical: 10,
      paddingHorizontal: 4,
      minHeight: 44,
    },
    menuItemText: {
      fontSize: r.rf(15),
      fontFamily: "Inter_500Medium",
      color: Colors.text,
    },
    sectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 10,
      paddingHorizontal: 4,
      minHeight: 44,
    },
    sectionHeaderLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    sectionHeaderText: {
      fontSize: r.rf(15),
      fontFamily: "Inter_600SemiBold",
      color: Colors.text,
    },
    sectionBody: {
      paddingLeft: 8,
      gap: 2,
    },
    settingRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 8,
      paddingHorizontal: 4,
      minHeight: 44,
    },
    settingInfo: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      flex: 1,
    },
    settingLabel: {
      fontSize: r.rf(14),
      fontFamily: "Inter_500Medium",
      color: Colors.text,
    },
    comingSoon: {
      fontSize: r.rf(11),
      fontFamily: "Inter_400Regular",
      color: Colors.textTertiary,
      marginTop: 1,
    },
    radiusPills: {
      flexDirection: "row",
      gap: 6,
      paddingHorizontal: 4,
      paddingBottom: 8,
      flexWrap: "wrap",
    },
    radiusPill: {
      paddingHorizontal: r.rs(12),
      paddingVertical: 6,
      borderRadius: 16,
      backgroundColor: Colors.surfaceSecondary,
      borderWidth: 1,
      borderColor: Colors.border,
    },
    radiusPillActive: {
      backgroundColor: Colors.primaryLight,
      borderColor: Colors.primary,
    },
    radiusPillText: {
      fontSize: r.rf(13),
      fontFamily: "Inter_500Medium",
      color: Colors.textSecondary,
    },
    radiusPillTextActive: {
      color: Colors.primary,
    },
    authActions: {
      gap: 10,
      paddingTop: 20,
    },
    loginBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      paddingVertical: r.rs(14),
      borderRadius: 12,
      backgroundColor: Colors.primary,
      minHeight: 48,
    },
    loginBtnText: {
      fontSize: r.rf(15),
      fontFamily: "Inter_600SemiBold",
      color: "#FFF",
    },
    guestBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      paddingVertical: r.rs(14),
      borderRadius: 12,
      backgroundColor: Colors.primaryLight,
      borderWidth: 1,
      borderColor: Colors.primary,
      minHeight: 48,
    },
    guestBtnText: {
      fontSize: r.rf(15),
      fontFamily: "Inter_600SemiBold",
      color: Colors.primary,
    },
    supportOverlay: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: Colors.overlay,
      paddingHorizontal: 24,
    },
    supportCard: {
      backgroundColor: Colors.surface,
      borderRadius: 20,
      padding: 24,
      width: "100%",
      maxWidth: 400,
    },
    supportTitle: {
      fontSize: r.rf(18),
      fontFamily: "Inter_700Bold",
      color: Colors.text,
      marginBottom: 4,
    },
    supportSubtitle: {
      fontSize: r.rf(13),
      fontFamily: "Inter_400Regular",
      color: Colors.textSecondary,
      marginBottom: 16,
    },
    supportFieldLabel: {
      fontSize: r.rf(13),
      fontFamily: "Inter_600SemiBold",
      color: Colors.textSecondary,
      marginBottom: 6,
    },
    supportSubjectInput: {
      borderWidth: 1,
      borderColor: Colors.border,
      borderRadius: 12,
      padding: 12,
      fontSize: r.rf(14),
      fontFamily: "Inter_400Regular",
      color: Colors.text,
      backgroundColor: Colors.surfaceSecondary,
      marginBottom: 12,
    },
    supportInput: {
      borderWidth: 1,
      borderColor: Colors.border,
      borderRadius: 12,
      padding: 12,
      fontSize: r.rf(14),
      fontFamily: "Inter_400Regular",
      color: Colors.text,
      minHeight: 120,
      backgroundColor: Colors.surfaceSecondary,
      marginBottom: 16,
    },
    supportActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 10,
    },
    supportCancelBtn: {
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 10,
      minHeight: 44,
      justifyContent: "center",
    },
    supportCancelText: {
      fontSize: r.rf(14),
      fontFamily: "Inter_500Medium",
      color: Colors.textSecondary,
    },
    supportSendBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingVertical: 10,
      paddingHorizontal: 18,
      borderRadius: 10,
      backgroundColor: Colors.primary,
      minHeight: 44,
    },
    supportSendBtnDisabled: {
      opacity: 0.5,
    },
    supportSendText: {
      fontSize: r.rf(14),
      fontFamily: "Inter_600SemiBold",
      color: "#FFF",
    },
  });
}
