import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";
import type { ResponsiveUtils } from "@/lib/responsive";

export function createStyles(r: ResponsiveUtils) {
  const avatarSize = r.isTablet ? r.rs(140) : r.isLargePhone ? 116 : 100;

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: Colors.background,
    },
    content: {
      paddingHorizontal: r.isTablet ? r.wp(8) : r.rs(20),
      paddingBottom: 28,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: r.isTablet ? r.wp(8) : r.rs(20),
      paddingBottom: 18,
    },
    headerBtn: {
      width: Math.max(r.rs(40), 44),
      height: Math.max(r.rs(40), 44),
      borderRadius: r.rs(20),
      backgroundColor: Colors.surface,
      borderWidth: 1,
      borderColor: Colors.borderLight,
      alignItems: "center",
      justifyContent: "center",
    },
    headerTitle: {
      fontSize: r.rf(20),
      fontFamily: "Inter_700Bold",
      color: Colors.text,
    },
    headerSpacer: {
      width: Math.max(r.rs(40), 44),
    },
    profileCard: {
      backgroundColor: Colors.surface,
      borderRadius: 24,
      padding: r.rs(24),
      alignItems: "center",
      borderWidth: 1,
      borderColor: Colors.borderLight,
    },
    avatarWrap: {
      width: avatarSize,
      height: avatarSize,
      borderRadius: avatarSize / 2,
      backgroundColor: Colors.primaryLight,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
    },
    avatarImage: {
      width: "100%",
      height: "100%",
    },
    avatarPlaceholder: {
      alignItems: "center",
      justifyContent: "center",
    },
    badgePill: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginTop: 14,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: Colors.accentLight,
    },
    badgePillText: {
      fontSize: r.rf(13),
      fontFamily: "Inter_600SemiBold",
      color: Colors.accent,
    },
    profileName: {
      marginTop: 14,
      fontSize: r.rf(28),
      fontFamily: "Inter_700Bold",
      color: Colors.text,
      textAlign: "center",
    },
    profileEmail: {
      marginTop: 6,
      fontSize: r.rf(14),
      fontFamily: "Inter_400Regular",
      color: Colors.textSecondary,
      textAlign: "center",
    },
    editPictureBtn: {
      marginTop: 16,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 999,
      backgroundColor: Colors.primaryLight,
      borderWidth: 1,
      borderColor: Colors.primary,
      minHeight: 44,
    },
    editPictureText: {
      fontSize: r.rf(14),
      fontFamily: "Inter_600SemiBold",
      color: Colors.primary,
    },
    section: {
      marginTop: 18,
      backgroundColor: Colors.surface,
      borderRadius: 24,
      padding: r.rs(20),
      borderWidth: 1,
      borderColor: Colors.borderLight,
    },
    sectionTitle: {
      fontSize: r.rf(18),
      fontFamily: "Inter_700Bold",
      color: Colors.text,
    },
    sectionSubtitle: {
      marginTop: 6,
      fontSize: r.rf(13),
      fontFamily: "Inter_400Regular",
      color: Colors.textSecondary,
      lineHeight: r.rf(20),
    },
    badgeGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 12,
      marginTop: 18,
    },
    badgeItem: {
      width: r.isTablet ? "30%" : "47%",
      borderRadius: 18,
      padding: r.rs(14),
      backgroundColor: Colors.surfaceSecondary,
      borderWidth: 1,
      borderColor: Colors.borderLight,
    },
    badgeItemEarned: {
      backgroundColor: Colors.primaryLight,
      borderColor: Colors.primary,
    },
    badgeIconWrap: {
      width: r.rs(38),
      height: r.rs(38),
      borderRadius: r.rs(19),
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: Colors.surface,
    },
    badgeLabel: {
      marginTop: 12,
      fontSize: r.rf(14),
      fontFamily: "Inter_600SemiBold",
      color: Colors.text,
    },
    badgeStatus: {
      marginTop: 6,
      fontSize: r.rf(12),
      fontFamily: "Inter_500Medium",
      color: Colors.textSecondary,
    },
    statGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 12,
      marginTop: 18,
    },
    statCard: {
      width: r.isTablet ? "30%" : "47%",
      borderRadius: 18,
      padding: r.rs(16),
      backgroundColor: Colors.surfaceSecondary,
    },
    statValue: {
      fontSize: r.rf(28),
      fontFamily: "Inter_700Bold",
      color: Colors.text,
    },
    statLabel: {
      marginTop: 8,
      fontSize: r.rf(13),
      fontFamily: "Inter_500Medium",
      color: Colors.textSecondary,
    },
    button: {
      marginTop: 16,
      borderRadius: 18,
      paddingVertical: r.rs(16),
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      gap: 10,
      minHeight: 48,
    },
    primaryButton: {
      backgroundColor: Colors.primary,
    },
    secondaryButton: {
      backgroundColor: Colors.surface,
      borderWidth: 1,
      borderColor: Colors.border,
    },
    dangerButton: {
      backgroundColor: Colors.surface,
      borderWidth: 1,
      borderColor: "#FECACA",
    },
    primaryButtonText: {
      fontSize: r.rf(16),
      fontFamily: "Inter_700Bold",
      color: "#FFF",
    },
    secondaryButtonText: {
      fontSize: r.rf(16),
      fontFamily: "Inter_700Bold",
      color: Colors.text,
    },
    dangerButtonText: {
      fontSize: r.rf(16),
      fontFamily: "Inter_700Bold",
      color: Colors.danger,
    },
    helperText: {
      marginTop: 14,
      fontSize: r.rf(13),
      fontFamily: "Inter_400Regular",
      color: Colors.textSecondary,
      lineHeight: r.rf(20),
    },
    errorText: {
      marginTop: 12,
      fontSize: r.rf(13),
      fontFamily: "Inter_500Medium",
      color: Colors.danger,
    },
  });
}
