import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";
import type { ResponsiveUtils } from "@/lib/responsive";

export function createStyles(r: ResponsiveUtils) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: Colors.background,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: r.rs(16),
      paddingVertical: 12,
      maxWidth: r.isTablet ? 600 : undefined,
      alignSelf: r.isTablet ? ("center" as const) : undefined,
      width: "100%",
    },
    backBtn: {
      width: Math.max(r.rs(40), 44),
      height: Math.max(r.rs(40), 44),
      borderRadius: r.rs(20),
      backgroundColor: Colors.surfaceSecondary,
      alignItems: "center",
      justifyContent: "center",
    },
    headerTitle: {
      flex: 1,
      textAlign: "center",
      fontSize: r.rf(17),
      fontFamily: "Inter_600SemiBold",
      color: Colors.text,
    },
    closeBtn: {
      width: Math.max(r.rs(40), 44),
      height: Math.max(r.rs(40), 44),
      borderRadius: r.rs(20),
      backgroundColor: Colors.surfaceSecondary,
      alignItems: "center",
      justifyContent: "center",
    },
    steps: {
      flexDirection: "row",
      justifyContent: "center",
      gap: 8,
      paddingVertical: 12,
    },
    stepDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: Colors.border,
    },
    stepDotActive: {
      backgroundColor: Colors.primaryLight,
      width: 8,
    },
    stepDotCurrent: {
      backgroundColor: Colors.primary,
      width: 24,
      borderRadius: 4,
    },
    stepContent: {
      flex: 1,
      paddingHorizontal: r.rs(20),
      maxWidth: r.isTablet ? 600 : undefined,
      alignSelf: r.isTablet ? ("center" as const) : undefined,
      width: "100%",
    },
    step2ScrollContent: {
      paddingTop: 4,
    },
    stepTitle: {
      fontSize: r.rf(24),
      fontFamily: "Inter_700Bold",
      color: Colors.text,
      marginBottom: 4,
    },
    stepSubtitle: {
      fontSize: r.rf(14),
      fontFamily: "Inter_400Regular",
      color: Colors.textSecondary,
      marginBottom: 10,
    },
    categoryGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      paddingBottom: 40,
    },
    categoryItem: {
      width: r.isTablet ? "22%" : "30%",
      aspectRatio: 1,
      backgroundColor: Colors.surface,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      borderWidth: 2,
      borderColor: "transparent",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 1,
    },
    categoryItemSelected: {
      borderColor: Colors.primary,
      backgroundColor: Colors.primaryLight,
    },
    categoryLabel: {
      fontSize: r.rf(11),
      fontFamily: "Inter_500Medium",
      color: Colors.text,
      textAlign: "center",
      paddingHorizontal: 4,
    },
    photoActions: {
      flexDirection: "row",
      gap: 8,
      marginTop: 6,
      width: "100%",
    },
    photoActionBtn: {
      flex: 1,
      alignItems: "center",
      gap: 8,
    },
    photoActionIcon: {
      width: r.rs(72),
      height: r.rs(72),
      borderRadius: 20,
      backgroundColor: Colors.primaryLight,
      alignItems: "center",
      justifyContent: "center",
    },
    photoActionText: {
      fontSize: r.rf(14),
      fontFamily: "Inter_500Medium",
      color: Colors.text,
    },
    photoPreview: {
      width: "100%",
      marginTop: 12,
      borderRadius: 16,
      overflow: "hidden",
      position: "relative",
    },
    previewImage: {
      width: "100%",
      height: r.isTablet ? r.hp(28) : r.rs(240),
      borderRadius: 16,
    },
    removePhotoBtn: {
      position: "absolute",
      top: 12,
      right: 12,
      zIndex: 2,
    },
    photoPreviewActions: {
      position: "absolute",
      left: 12,
      right: 12,
      bottom: 12,
      flexDirection: "row",
      gap: 10,
    },
    photoPreviewActionBtn: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      paddingVertical: 10,
      borderRadius: 12,
      backgroundColor: "rgba(255,255,255,0.94)",
      minHeight: 44,
    },
    photoPreviewActionText: {
      fontSize: r.rf(13),
      fontFamily: "Inter_600SemiBold",
      color: Colors.primary,
    },
    navButtons: {
      flexDirection: "row",
      justifyContent: "flex-end",
      marginTop: 24,
    },
    skipBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingVertical: 12,
      paddingHorizontal: r.rs(20),
      borderRadius: 12,
      backgroundColor: Colors.primaryLight,
      minHeight: 44,
    },
    skipBtnText: {
      fontSize: r.rf(15),
      fontFamily: "Inter_600SemiBold",
      color: Colors.primary,
    },
    confirmCard: {
      backgroundColor: Colors.surface,
      borderRadius: 20,
      padding: r.rs(24),
      alignItems: "center",
      gap: 8,
      marginTop: 4,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 2,
    },
    confirmCategory: {
      fontSize: r.rf(20),
      fontFamily: "Inter_700Bold",
      color: Colors.text,
    },
    confirmPhoto: {
      width: "100%",
      height: r.rs(160),
      borderRadius: 12,
    },
    confirmInfo: {
      width: "100%",
      gap: 8,
      marginTop: 4,
    },
    confirmInfoRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    confirmInfoText: {
      flex: 1,
      fontSize: r.rf(13),
      fontFamily: "Inter_400Regular",
      color: Colors.textSecondary,
    },
    submitBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      paddingVertical: r.rs(14),
      borderRadius: 14,
      backgroundColor: Colors.primary,
      marginTop: 5,
      minHeight: 48,
    },
    submitBtnDisabled: {
      opacity: 0.6,
    },
    submitBtnText: {
      fontSize: r.rf(16),
      fontFamily: "Inter_600SemiBold",
      color: "#FFF",
    },
  });
}
